# configs/config.yaml

# Hydra configs
hydra:
  job_logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      simple:
        format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    handlers:
      file:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers: [file]

# ---------------------------------------------------------------------------------------------------
# Main configs
dataset:
  name: "custom"
  path: "data/augmented/"
  saved_images: false

model:
  name: "srresunet"
  pretrained: false
  in_channels: 3
  out_channels: 3
  num_filters: 32
  num_residuals: 2
  upscale_factor: 4  # high_res image is 4x the size of low_res image


training:
  epochs: 100
  batch_size: 32
  loss: "l1"
  optimizer: "adam"
  learning_rate: 0.0001
  lr_scheduler_enabled: false
  lr_step_size: 10
  lr_gamma: 0.1

other:
  log_print: true
  wandb: false
  #wandb: tempSuperRes
  save_val_images_local: true
  run_testing: true
  testing_loss: true
  run_testing_only: true
  testing_only_model_path: "outputs/2025-05-29/22-54-23/models/"