dataset:
  name: custom
  path: data/augmented/
  saved_images: false
model:
  name: srresunet
  pretrained: false
  in_channels: 3
  out_channels: 3
  num_filters: 32
  num_residuals: 2
  upscale_factor: 4
training:
  epochs: 100
  batch_size: 32
  loss: l1
  optimizer: adam
  learning_rate: 0.0001
  lr_scheduler_enabled: false
  lr_step_size: 10
  lr_gamma: 0.1
other:
  log_print: true
  wandb: tempSuperRes
  save_val_images_local: true
  run_testing: true
  testing_loss: true
  run_testing_only: false
